# Copyright 2018 REMME
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------

version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build Docker images
          command: make build_docker
      - run:
          name: Run tests
          command: make test
  deploy:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build Docker images
          command: make build_docker
      - run:
          name: Push to Docker
          command: |
            docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD && \
            docker tag remme/remme-core:latest remme/remme-core:$CIRCLE_TAG && \
            docker tag remme/remme-core-dev:latest remme/remme-core-dev:$CIRCLE_TAG && \
            docker push remme/remme-core && \
            docker push remme/remme-core-dev

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v?\d+.\d+.\d+(-(alpha|beta|rc)(.\d+)?)?$/
            branches:
              ignore: /.*/
